- 1.1 入门

In [14]:
import torch
from numpy.conftest import dtype

# print(torch.__version__)

x = torch.arange(12)
print(x)
print(x.shape) # 访问张量的形状
print(x.numel()) # 访问张量的元素个数
# new_x = x.reshape(3, 4) # reshape函数, 改变一个张量的形状而不改变元素数量和元素值
# new_x = x.reshape(-1, 4) # 和上面效果一样
new_x = x.reshape(3, -1) # 和上面效果一样
print(new_x)
print(new_x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [7]:
# 创建 形状为 2, 3, 4, 所有元素都是0的张量
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# 创建 形状为 2, 3, 4, 所有元素都是0的张量
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
# 每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
r_x = torch.randn(3, 4)
print(r_x)
# print(r_x.sum())

tensor([[-1.8897,  0.0402, -0.3216,  0.2580],
        [-0.6214, -0.3166,  0.6893, -0.0964],
        [ 0.5494, -1.6570, -1.2573,  0.6570]])
tensor(-3.9661)


In [11]:
# 可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。 在这里，最外层的列表对应于轴0，内层的列表对应于轴1

torch.tensor([[0, 1, 2], [3, 4, 5]])

tensor([[0, 1, 2],
        [3, 4, 5]])

- 1.2 运算符
```text
  对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算 -- 不同形状会有广播机制

In [16]:
import torch

x = torch.tensor([1., 2., 4., 8.])
y = torch.tensor([2., 2., 2., 2.])

# x 和 y 具有相同的形状, 对 x 、y 进行的运算, 都可以升级为按元素运算
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


- “按元素”方式可以应用更多的计算，包括像求幂这样的一元运算符

In [17]:
import torch

x = torch.tensor([1., 2., 4., 8.])
print(torch.exp(x))

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


- concatenate 函数将多个张量连接在一起, 可以指定按照哪个维度来连接, 比如: dim=0 表示在0维上连接(按行连接), dim=1 表示在1维上连接(按列连接) -- torch.cat 在指定维度上连接张量时，要求除连接维度外的其他维度大小必须完全一致

In [46]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0))
print(torch.cat((X, Y), dim=1))


X_2 = torch.arange(12).reshape(3, 4)
Y_2 = torch.arange(12).reshape(4, 3)
print(torch.cat((X_2, Y_2), dim=0))  # RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 4 but got size 3 for tensor number 1 in the list

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 4 but got size 3 for tensor number 1 in the list.

- 通过逻辑运算符构建二元张量 如果X和Y在该位置相等，则新张量中相应项的值为1, 意味着逻辑语句X == Y在该位置处为真，否则该位置为0

In [87]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X == Y)
print(X < Y)
print(X > Y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


- 求和, 对张量中的所有元素进行求和，会产生一个单元素张量

In [22]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print(torch.sum(X))

tensor(66.)


- 1.3 广播机制
```text
1.2节举的例子, 要求两个张量X和Y具有相同的形状。
但是在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作

1) 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2) 对生成的数组执行按元素操作
3) 一般情况下沿着数组中长度为1的轴进行广播 (通过下面的例子可以观察到, 需要广播的数组长度为1, 如果不是, 会报错)

In [118]:
import torch
# a = torch.arange(6).reshape(3, 2)
a = torch.arange(3).reshape(3, 1)
print(a)
b = torch.arange(2).reshape(1, 2)
# b = torch.tensor([[0, 1], [2, 3]])
print(b)
print("*" * 20)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
********************


In [119]:
print(a + b)
# print(torch.cat((a, b), dim=0))

tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [95]:
import torch
a = torch.arange(6).reshape(1, 3, 2)
print(a)
b = torch.arange(2).reshape(1, 2)
# b = torch.tensor([[0, 1], [2, 3]])
print(b)
print( a + b)

tensor([[[0, 1],
         [2, 3],
         [4, 5]]])
tensor([[0, 1]])
tensor([[[0, 2],
         [2, 4],
         [4, 6]]])


- 1.4. 索引和切片

In [68]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)

print(X)
print(X[-1])
print(X[1:3])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


- 除读取外，我们还可以通过指定索引来将元素写入矩阵

In [69]:
X[1, 2] = 9 # 将 2行 3列的数改为 9
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


- 为多个元素赋值相同的值

In [71]:
X[0:2, :] = 12 # 将 0行 1行 的所有数改为 12
print(X)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


- 1.5. 节省内存
```text
运行一些操作可能会导致为新结果分配内存

In [77]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

before = id(Y)
Y = Y + X
after = id(Y)

print(before)
print(after)
print(before == after)

print("-" * 20)
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = Y + X
print('id(Z):', id(Z))

3038849999936
3038849999936
True
--------------------
id(Z): 3038849998416
id(Z): 3038849998416


- 1.6. 转换为其他Python对象
```text
将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。 torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量

In [85]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
A = X.numpy()
# print(A)

B = torch.tensor(A)
print(B)

print(type(A))
print(type(B))

# 张量 和 numpy 数之间进行转换, 底层公用了内存, 改变一个张量, 会同时改变另一个张量
X[0, 0] = 10 # A 由 X.numpy 生成, 改变 X, 会同时改变 A
print(A)
print(X)
print(B) # 不会改变

print("*" * 50)


A[0, 0] = 20
print(A)
print(B) # 不会改变
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
[[10.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tensor([[10.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
**************************************************
[[20.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[20.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


- 将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数

In [86]:
import torch

a = torch.tensor([3.5])
print(a , a.item(), float(a), int(a))

tensor([3.5000]) 3.5 3.5 3


- 2. 数据预处理 -- 读取数据集


In [97]:
import os

# 创建文件夹
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w', encoding='utf-8') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

- 导入pandas包并调用read_csv函数。从创建的CSV文件中加载原始数据集, 该数据集有四行三列, 其中每行描述了房间数量（“NumRooms”）、巷子类型（“Alley”）和房屋价格（“Price”）

In [99]:
import pandas as pd

data_file = os.path.join('..', 'data', 'house_tiny.csv')
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


- 2.2. 处理缺失值
```text
注意，“NaN”项代表缺失值。 为了处理缺失的数据，典型的方法包括插值法和删除法，
- 插值法: 用一个替代值弥补缺失值
- 删除法: 则直接忽略缺失值

In [9]:
import pandas as pd
import os

data_file = os.path.join('..', 'data', 'house_tiny.csv')
data = pd.read_csv(data_file)

#  通过位置索引iloc，我们将data分成inputs和outputs， 其中前者为data的前两列，而后者为data的最后一列。 对于inputs中缺少的数值，我们用同一列的均值替换“NaN”项
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# print(inputs)
# print(outputs)
inputs = pd.get_dummies(inputs, dummy_na=True) # 显示 nan 数据列, dummy_na 用于控制是否为缺失值 NaN 创建虚拟变量 False 表示不处理缺失值 NaN  True 表示处理缺失值 NaN
# inputs = pd.get_dummies(inputs)
# print(inputs)
inputs = inputs.fillna(inputs.mean())
print(inputs)
# print(type(inputs)) # <class 'pandas.core.frame.DataFrame'>



   NumRooms  Alley_Pave
0       3.0        True
1       2.0       False
2       4.0       False
3       3.0       False


In [123]:
import torch

x = inputs.to_numpy(dtype=float)
x = torch.tensor(x)
# print(x) # 4 * 3
y = outputs.to_numpy(dtype=float)
y = torch.tensor(y)
# print(y) # 1 * 4

print(x, y) # 广播机制

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64) tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


- 2.5. 练习
    - 删除缺失值最多的列

In [151]:
import pandas as pd
import os

file_path = os.path.join('..', 'data', 'house_tiny.csv')
data = pd.read_csv(file_path)


# miss_columns = data.isnull().sum() # 统计缺失值的数量
miss_columns = data.isna().sum() # isnull 是 isna 的别名
# print(miss_columns) # 统计列缺失值数量
# print(miss_columns.idxmax())
# print(type(miss_columns)) # <class 'pandas.core.series.Series'>

# 删除 NaN 最多的列
'''
inplace 作用
False, 对数据 data 做copy
True, 直接在 data 的基础上错操作, 返回None
'''
# data_cleaned = data.drop(miss_columns.idxmax(), axis=1, inplace=False)
data_cleaned = data.drop(columns=[miss_columns.idxmax()], axis=1, inplace=False)
# print(data)
# print(data_cleaned)

numeric_columns = data_cleaned.select_dtypes(include=['number']).columns # 找到包含数字的列明
# print(numeric_columns)
# pandas 的正常行为：fillna() 只会替换 NaN 值，不会修改已有的有效数据
data_cleaned[numeric_columns] = data_cleaned[numeric_columns].fillna(data_cleaned[numeric_columns].mean())
# print(type(data_cleaned)) # <class 'pandas.core.frame.DataFrame'>
print(data_cleaned)

   NumRooms   Price
0       3.0  127500
1       2.0  106000
2       4.0  178100
3       3.0  140000


    - 将预处理后的数据集转换为张量格式

In [161]:
# 在上面处理的结果上, 继续做这个需求

data_cleaned_numpy = data_cleaned.to_numpy(dtype=float)
# print(data_cleaned_numpy)
data_cleaned_torch = torch.tensor(data_cleaned_numpy)
print(data_cleaned_torch)
print(data_cleaned_torch.shape)

tensor([[3.0000e+00, 1.2750e+05],
        [2.0000e+00, 1.0600e+05],
        [4.0000e+00, 1.7810e+05],
        [3.0000e+00, 1.4000e+05]], dtype=torch.float64)
torch.Size([4, 2])


- 3. 线性代数
    - 3.1. 标量
    ```text
不随空间、形状变化而改变,
张量表示方式: 标量由只有一个元素的张量表示

In [162]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
print(x + y, x - y, x * y, x / y, x ** y)

tensor(5.) tensor(1.) tensor(6.) tensor(1.5000) tensor(9.)


- 3.2. 向量
```text
向量可以被视为标量值组成的列表。 这些标量值被称为向量的元素（element）或分量（component）
通过一维张量表示向量
单个向量的默认方向是列向量
大量文献认为列向量是向量的默认方向

In [170]:
import torch

# x = torch.arange(4)
x = torch.tensor([2,2,2,2])
print(x)
print(x[3])

tensor([2, 2, 2, 2])
tensor(2)


- 长度、维度和形状

In [172]:
'''
向量场景下 或 一维数组张量场景下
张量的某个轴的维数就是这个轴的长度。 len() 、shape
'''
# 长度 元素的数量
print(len(x))
print(x.shape)
print(x.ndim)

print('*' * 30)
# 下面示例代码 x2 是矩阵, 不是向量
x2 = torch.arange(12).reshape(3, 4)
print(len(x2)) # 3 axis = 0 对应的行数
# print(x2.t()) # 转置
print(x2.shape)
print(x2.ndim)

4
torch.Size([4])
******************************
3
torch.Size([3, 4])
2


- 3.3. 矩阵
```text
正如向量将标量从零阶推广到一阶，矩阵将向量从一阶推广到二阶


In [173]:
import torch

A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

- 矩阵转置

In [178]:
'''
交换矩阵的行和列时，结果称为矩阵的转置（transpose）, a.t() 来获取转置
'''

print(A.T)
# print(A.t())
# print(A.transpose(0, 1))
# print(torch.transpose(A, 0, 1)) # 交换 ndim0、 ndim1 的数据

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


- 对称矩阵（symmetric matrix） -- 矩阵的转置等于自身, 方阵的一种特殊矩阵

In [179]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [181]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

- 3.4. 张量
```text
张量是描述具有任意数量轴的n维数组的通用方法
- 向量是一阶张量
- 矩阵是二阶张量

In [182]:
import torch

X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

- 3.5. 张量算法的基本性质
```text
标量、向量、矩阵和任意数量轴的张量有一些实用的属性
1. 任何按元素的一元运算都不会改变其操作数的形状
2. 给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量 -- 可以参考第二节

In [185]:
import torch

A = torch.arange(20).reshape(5, 4)
B = A.clone()
print(A)
# print(B)
print(A + B)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]])


In [186]:
'''
两个矩阵的按元素乘法称为Hadamard积（Hadamard product）
'''
# 矩阵A 和 矩阵B Hadamard积
print(A * B)

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])


In [188]:
'''
将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘
'''
import torch

a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(X)
print(a + X)
print((a * X).shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


- 3.6. 降维
```text
可以对任意张量进行的一个有用的操作是计算其元素的和

In [8]:
# import numpy as np
#
# x = np.arange(4)
# print(x, x.sum())

import torch

x = torch.arange(4, dtype=torch.float32)
print(x, x.sum())

tensor([0, 1, 2, 3]) tensor(6)


In [9]:
'''
可以表示任意形状张量的元素和
'''
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A.shape, A.sum())

torch.Size([5, 4]) tensor(190.)


In [11]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A_sum_axis0 = A.sum(axis=0) # 列求和
print(A, A_sum_axis0, A_sum_axis0.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([40., 45., 50., 55.]) torch.Size([4])


In [12]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A_sum_axis1 = A.sum(axis=1) # 行求和
print(A, A_sum_axis1, A_sum_axis1.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])


In [13]:
'''
沿着行、列求和, 等价于对所有元素求和
'''

import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# A_aum_all = A.sum(axis=[0, 1])
A_sum_all = torch.sum(A, (0, 1))
print(A, A_sum_all)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor(190.)


In [15]:
'''
与求和相关的量是平均值（mean或average）
'''
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A, A.mean(), A.mean().shape, A.sum()/A.numel()) # A.mean().shape 没有维度的标量

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor(9.5000) torch.Size([]) tensor(9.5000)


In [18]:
'''
计算平均值的函数也可以沿指定轴降低张量的维度
'''
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A, A.mean(axis=0), A.sum(axis=0)/A.shape[0])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([ 8.,  9., 10., 11.]) tensor([ 8.,  9., 10., 11.])


- 3.6.1. 非降维求和

In [25]:
'''
在调用函数来计算总和或均值时保持轴数不变会很有用
'''
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

print(A, A.sum(), A.sum(axis=0))
A_sum_axis0 = A.sum(axis=0, keepdim=True)
print(A_sum_axis0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor(190.) tensor([40., 45., 50., 55.])
tensor([[40., 45., 50., 55.]])


In [26]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

print(A, A.sum(), A.sum(axis=1))
A_sum_axis1 = A.sum(axis=1, keepdim=True) # keepdim 保持张量的维度
print(A_sum_axis1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor(190.) tensor([ 6., 22., 38., 54., 70.])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [27]:
'''
在上面步骤下, A.shape = (5,4)
A_sum_axis1.shape = (5,1)
A 和 A_sum_axis1 进行运算时可以通过广播的方式进行处理
'''
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A_sum_axis1 = A.sum(axis=1, keepdim=True) # keepdim 保持张量的维度
print(A, A_sum_axis1, A/A_sum_axis1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]]) tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [32]:
'''
累加求和 想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度
'''
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# print(A, A.cumsum(axis=0), A.sum(axis=0))
print(A, A.cumsum(axis=1), A.sum(axis=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]]) tensor([ 6., 22., 38., 54., 70.])


- 3.7. 点积（Dot Product）
```text
点积: 相同位置的按元素乘积的和
torch.dot 执行的是向量点积（也称为内积或标量积）, 是对应元素相乘后求和, 比如下面示例 # 0*1 + 1*1 + 2*1 + 3*1 = 0 + 1 + 2 + 3 = 6

In [36]:
import torch

x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)

print(x, y, torch.dot(x, y))

# 可以通过执行按元素乘法，然后进行求和来表示两个向量的点积：
print(x * y, torch.sum(x * y))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)
tensor([0., 1., 2., 3.]) tensor(6.)


- 3.8. 矩阵-向量积

矩阵向量积Ax是一个长度为m的列向量， 其第i个元素是点积 torch.dot(A(i), x)
A = m * n 的矩阵
x = 1 * n
第i个元素是, A的第i行的 n 个列元素 和 x 进行点积的结果

In [37]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4, dtype=torch.float32)

print(A, x, torch.mv(A, x))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([0., 1., 2., 3.]) tensor([ 14.,  38.,  62.,  86., 110.])


- 矩阵-矩阵乘法
```text
点积 -> 矩阵向量积 -> 矩阵-矩阵乘法
矩阵-矩阵 乘法: AB, A=m*n, B=n*k  计算结果 C=m * k, C[i,j] = A[i,:] * B[:,j] 表示 A的第i行所有n个列元素 和 B的j列，所有的行元素继续点积的值
C[i, :] 第i行所有元素 = A[i,:] * B[:, :] i行每列的元素 = A矩阵第i行的所有元素分别和b矩阵k列的值做 矩阵-向量积


矩阵-矩阵乘法可以简单地称为矩阵乘法，不应与“Hadamard积”混淆
- 矩阵乘法 torch.mm(A, B)
- Hadamard积 A * B

In [38]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = torch.ones(4, 3)

print(A, B, torch.mm(A, B))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


- 3.10. 范数
```text
Ln范数, 所有元素的n次方之和再开n次方

In [39]:
# L2 范数, 所有元素平方之和再开方
import torch

u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [40]:
# L1 范数, 所有元素绝对值之和
torch.abs(u).sum()

tensor(7.)

In [42]:
# Frobenius 范数, 所有元素平方之和再开2次方
print(torch.ones(4, 9))

print(torch.norm(torch.ones(4, 9))) # L2 范数, 所有元素平方和之后, 再开2次方(平方根) = 6

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor(6.)


- 练习
    - 证明一个矩阵A的转置的转置是A
    - 给出两个矩阵A和B, 证明“它们转置的和”等于“它们和的转置”，
    - 给定任意方阵A, A + A的转置 总是对称的吗?为什么?
    - 本节中定义了形状(2,3,4)的张量X。len(X)的输出结果是什么
    - 对于任意形状的张量X,len(X)是否总是对应于X特定轴的长度?这个轴是什么?
    - 运行A/A.sum(axis=1)，看看会发生什么。请分析一下原因？
    - 考虑一个具有形状(2,3,4)的张量，在轴0、1、2上的求和输出是什么形状?
    - 为linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?

In [43]:
# 证明一个矩阵A的转置的转置是A
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

print(A == A.T.T)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


- 4. 微积分
- 4.1. 导数和微分
```text
做下面的测试, 安装相关依赖
1. d2l https://repo.huaweicloud.com/repository/pypi/simple/d2l/ 这里下载的是 d2l-0.17.6-py3-none-any.whl, 安装过程中可能会提示依赖版本问题, 需要将压缩文件中的 d2l-0.17.6.dist-info/METADATA 版本依赖 == 改为 >=
2. torch、torchvision、torchaudio 因为使用的 torch 版本是2.4.1, 这里安装的 torchvision=0.19.1, torchaudio=2.4.1, 如果是其它版本, 可以网络查询下版本对应关系

In [2]:
# 解释导数, 假设 u=f(x)=3x^2 - 4x

%matplotlib inline
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l

# 定义 f(x)
def f(x):
    return 3 * x ** 2 - 4 *x

# 定义 f'(x)
'''
f 表示函数 f(x)
x 表示变量取的值
h 表示无限接近0的值
'''
def numerical_lim(f, x, h):
    return (f(x+h) - f(x))/h


h=0.1
for i in range(5):
    print(f'h={h:0.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


符号 d/dx 和 D 是微分运算符，表示微分操作。可以使用如下规则来对常见函数求微分
- 常见规则
    - DC = 0 C表示常量, 表示对常量求导
    - Dx^n = nx^(n-1) n是任意实数, 表示对 x^n 求导
    - De^x = e^x 表示对 e^x 求导
    - Dlogx = 1/x 表示对 logx 求导
- 常见法则
    - 乘法法则 d[f(x)g(x])/dx = f(x)g'(x) + f'(x)g(x) = f(x)d[g(x)]/dx + g(x)d[f(x)]/dx
    - 常数相乘法则 d|Cf(x)|/dx = Cf'(x)  其实可以这么理解: 常数求导为0 再结合乘法法则, 可以得到左边的式子
    - 加法法则 d|f(x) + g(x)|/dx = f'(x) + g'(x)
    - 除法法则 d[f(x)/g(x)]/dx = (g(x)f'(x) - f(x)g'(x))/g(x)^2 = (g(x)d|f(x)|/dx - f(x)d|g(x)|/dx)/g(x)^2


- 导数, 可以理解为曲线 u=f(x) 在x点切线的斜率

In [ ]:
# 注释 `#@save` 是一个特殊的标记，会将对应的函数、类或语句保存在d2l包中
# 解释导数, 假设 u=f(x)=3x^2 - 4x

In [ ]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

%matplotlib inline
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l

# 定义 f(x)
def f(x):
    return 3 * x ** 2 - 4 *x

# 定义 f'(x)
'''
f 表示函数 f(x)
x 表示变量取的值
h 表示无限接近0的值
'''
def numerical_lim(f, x, h):
    return (f(x+h) - f(x))/h


h=0.1
for i in range(5):
    print(f'h={h:0.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1

#@save
def use_svg_display(): #
    """使用svg格式在Jupyter中显示绘图"""
    backend_inline.set_matplotlib_formats('svg')

#@save
def set_figsize(figsize=(3.5, 2.5)):
    """设置matplotlib的图表大小"""
    use_svg_display()
    d2l.plt.rcParams['figure.figsize'] = figsize

#@save
def set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend):
    """设置matplotlib的轴"""
    axes.set_xlabel(xlabel)
    axes.set_ylabel(ylabel)
    axes.set_xlim(xlim)
    axes.set_ylim(ylim)
    axes.set_xscale(xscale)
    axes.set_yscale(yscale)
    if legend:
        axes.legend(legend)
    axes.grid()

def plot(X, Y=None, xlabel=None, ylabel=None, legend=None, xlim=None,
         ylim=None, xscale='linear', yscale='linear',
         fmts=('-', 'm--', 'g-.', 'r:'), figsize=(3.5, 2.5), axes=None):
    """定义一个plot函数来简洁地绘制多条曲线  绘制数据点"""
    if legend is None:
        legend = []

    set_figsize(figsize)
    axes = axes if axes else d2l.plt.gca()

    # 如果 x 有一个轴, 输出 True
    def has_one_axis(X):
        return  (hasattr(X,'ndim') and X.ndim == 1) or (isinstance(X, list) and not hasattr(X[0], '__len__'))

    if has_one_axis(X):
        X = [X]
    if Y is None:
        X, Y = [[]] * len(X), X
    elif has_one_axis(Y):
        Y = [Y]

    if len(X) != len(Y):
        X = X * len(Y) # 用这里的样例测试, len(Y)=2, X * len(Y) 表示X * 2 即复制2份
    axes.cla()

    for x, y, fmt in zip(X, Y, fmts):
        if len(x):
            axes.plot(x, y, fmt)
        else:
            axes.plot(y, fmt)

    set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)


# 绘制函数 u=f(x) 及其在 x=1 处的切线 y=2*x - 3
x = np.arange(0, 3, 0.1)
plot(x, [f(x), 2*x - 3], 'x', 'f(x)', legend=['f(x)', 'Tangent line(x=1)'])

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


- 4.2. 偏导数
```text
偏导数定义: 函数对某一变量的导数，保持其他变量不变

上面只讨论了仅含一个变量的函数的微分。 在深度学习中，函数通常依赖于许多变量。 因此，我们需要将微分的思想推广到多元函数(multivariate function)上

假设 y = f(x1, x2, x3,...,xn) 是一个具有n个变量的函数, y关于第i个参数xi的偏导数(partial derivative为)
∂y/∂xi = lim (f(x1,x2,...,xi-1, xi+h, xi+1,...,xn) - f(x1,x2,...,xi-1, xi, xi+1,...,xn))/h (h->0 无限趋近与0)

- 4.3. 梯度
```text
梯度(Gradient)：是一个向量, 由函数对所有变量的偏导数按顺序排列组成
梯度是将多元函数对每个变量的偏导数“连结”成一个向量，该向量综合了函数在所有方向上的变化率，并指向函数值增长最快的方向

设函数 f: R^n -> R 的输入是一个 n 维向量[x1,x2,...,xn]^T, 输出是一个标量。 函数f(x)相对于x的梯度是一个包含 n 个偏导数的向量 ∇f = [∂f/∂x1, ∂f/∂x2,...,∂f/∂xn]

- 5. 自动微分

In [12]:
'''
requires_grad_(True)：标记张量需要计算梯度
y.backward()：执行反向传播，自动计算梯度
x.grad：存储计算得到的梯度值
x.grad.zero_()：清零梯度，避免累积

xᵀx 表示点积（内积），结果是标量
x×xᵀ 表示外积，结果是[4,4]矩阵
'''

import torch

# 对函数 y = 2 * x^t * x 关于列向量求导
x = torch.arange(4, dtype=torch.float32) # 注意: 这里可以理解为声明了 x0 ~ x3 的列向量, 只是现在取值分别是 0,1,2,3
print(x)

# requires_grad 是字段, requires_grad_ 是方法
x.requires_grad_(True) # 等价于x=torch.arange(4.0,requires_grad=True)
print(x.grad) # 默认值 None

# 计算点积
y = 2 * torch.dot(x, x) # 0*0 + 1*1 + 2*2 + 3*3 = 0 + 1 + 4 + 9 = 14
print(y)

'''
x是一个长度为4的向量，计算x和x的点积，得到了我们赋值给y的标量输出。 接下来，通过调用反向传播函数来自动计算y关于x每个分量的梯度
'''
# 通过反向传播函数求梯度
y.backward()
print(x.grad)

# y=2 * x^t * x 关于x的梯度是4
print(x.grad == 4 * x)


# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
# print(x) # x 还是原来的值
y = x.sum()
y.backward()
print("x新梯度", x.grad)

tensor([0., 1., 2., 3.])
None
tensor(28., grad_fn=<MulBackward0>)
tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])
tensor([0., 1., 2., 3.], requires_grad=True)
x新梯度 tensor([1., 1., 1., 1.])


In [13]:
import torch

x = torch.arange(4, dtype=torch.float32, requires_grad=True)
print(x.grad)

y = x * x # 对应元素平方
y.sum().backward()
print(x.grad)

None
tensor([0., 2., 4., 6.])


In [17]:
import torch

x = torch.arange(4, dtype=torch.float32, requires_grad=True)
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
print(x.grad == u)


x.grad.zero_() # 清空梯度缓存
y.sum().backward()
print(x.grad == 2 * x)

tensor([True, True, True, True])
tensor([True, True, True, True])


- 5.4. Python控制流的梯度计算
```text
使用自动微分的一个好处是： 即使构建函数的计算图需要通过Python控制流（例如，条件、循环或任意函数调用），我们仍然可以计算得到的变量的梯度
```

In [29]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

'''
返回一个张量, 这个张量填充的是来自正太分布的随机值, 这个正太分布的均值是0,方差是1 (也成为标准正太分布)
'''
a = torch.randn(size=(), requires_grad=True)
print(a)
d = f(a)
# print(d)
d.backward()
# d.backward() # 报错 RuntimeError: Trying to backward through the graph a second time
# print(a.grad)
# print(d/a)
print(a.grad == d/a)


tensor(-1.1997, requires_grad=True)
tensor(True)


In [33]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.arange(4, dtype=torch.float32, requires_grad=True)
print(a)
d = f(a)
print(d)
d.sum().backward()
print(a.grad)

tensor([0., 1., 2., 3.], requires_grad=True)
tensor([   0.,  512., 1024., 1536.], grad_fn=<MulBackward0>)
tensor([512., 512., 512., 512.])


- 总结
```text
使用 深度学习框架计算指定变量梯度的思路
1. 首先将梯度附加到想要对其计算偏导数的变量上
2. 然后记录目标值的计算
3. 执行它的反向传播函数
4.并访问得到的梯度
```



- 概率
    - 基本概率论

In [2]:
%matplotlib inline
import torch
from torch.distributions import multinomial # 多项式
from d2l import torch as d2l

fair_probs = torch.ones([6])/6
# print(multinomial.Multinomial(1, fair_probs).sample()) # 返回一个从fair_probs中抽取的样本
# print(multinomial.Multinomial(100, fair_probs).sample()) # 返回100个从fair_probs中抽取的样本

# counts = multinomial.Multinomial(10000, fair_probs).sample()
# print(counts/10000)
counts = multinomial.Multinomial(20, fair_probs).sample((500,))
cum_counts = counts.cumsum(dim=0) # 做行累加, 当计算第i行时, 第i行结果 = 第i行的样本 + 第i-1行样本, 每行之和相加 = 20 * i
print(cum_counts)
estimates = cum_counts/cum_counts.sum(dim=1, keepdim=True)
print(estimates)



tensor([[   2.,    4.,    3.,    2.,    3.,    6.],
        [   9.,    7.,    4.,    6.,    6.,    8.],
        [  13.,   10.,    5.,    9.,   11.,   12.],
        ...,
        [1675., 1660., 1633., 1668., 1678., 1646.],
        [1679., 1662., 1634., 1671., 1683., 1651.],
        [1679., 1666., 1634., 1679., 1688., 1654.]])
tensor([[0.1000, 0.2000, 0.1500, 0.1000, 0.1500, 0.3000],
        [0.2250, 0.1750, 0.1000, 0.1500, 0.1500, 0.2000],
        [0.2167, 0.1667, 0.0833, 0.1500, 0.1833, 0.2000],
        ...,
        [0.1682, 0.1667, 0.1640, 0.1675, 0.1685, 0.1653],
        [0.1682, 0.1665, 0.1637, 0.1674, 0.1686, 0.1654],
        [0.1679, 0.1666, 0.1634, 0.1679, 0.1688, 0.1654]])


In [ ]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

%matplotlib inline
import torch
from torch.distributions import multinomial # 多项式
from d2l import torch as d2l

fair_probs = torch.ones([6])/6

counts = multinomial.Multinomial(10, fair_probs).sample((500,)) # 500组实验，每个样本有10个样本
cum_counts = counts.cumsum(dim=0)
print(cum_counts)
estimates = cum_counts/cum_counts.sum(dim=1, keepdim=True)
print( estimates)

d2l.set_figsize((6, 4.5))
for i in range(6):
    d2l.plt.plot(estimates[:, i].numpy(), label=("P(die=" + str(i + 1) + ")")) # [:, i] 表示取第i列

d2l.plt.axhline(y=0.167, color='black', linestyle='dashed')
d2l.plt.gca().set_xlabel('Groups of experiments')
d2l.plt.gca().set_ylabel('Estimated probability')
d2l.plt.legend();


tensor([[  2.,   1.,   0.,   1.,   3.,   3.],
        [  4.,   1.,   0.,   4.,   5.,   6.],
        [  6.,   3.,   0.,   7.,   6.,   8.],
        ...,
        [836., 838., 852., 823., 794., 837.],
        [838., 840., 854., 824., 796., 838.],
        [841., 843., 854., 825., 797., 840.]])
tensor([[0.2000, 0.1000, 0.0000, 0.1000, 0.3000, 0.3000],
        [0.2000, 0.0500, 0.0000, 0.2000, 0.2500, 0.3000],
        [0.2000, 0.1000, 0.0000, 0.2333, 0.2000, 0.2667],
        ...,
        [0.1679, 0.1683, 0.1711, 0.1653, 0.1594, 0.1681],
        [0.1679, 0.1683, 0.1711, 0.1651, 0.1595, 0.1679],
        [0.1682, 0.1686, 0.1708, 0.1650, 0.1594, 0.1680]])


- 6.2. 处理多个随机变量

- 查阅文档

In [193]:
tuple?

In [194]:
list??

In [2]:
import torch

print(dir(torch.distributions))

['AbsTransform', 'AffineTransform', 'Bernoulli', 'Beta', 'Binomial', 'CatTransform', 'Categorical', 'Cauchy', 'Chi2', 'ComposeTransform', 'ContinuousBernoulli', 'CorrCholeskyTransform', 'CumulativeDistributionTransform', 'Dirichlet', 'Distribution', 'ExpTransform', 'Exponential', 'ExponentialFamily', 'FisherSnedecor', 'Gamma', 'Geometric', 'Gumbel', 'HalfCauchy', 'HalfNormal', 'Independent', 'IndependentTransform', 'InverseGamma', 'Kumaraswamy', 'LKJCholesky', 'Laplace', 'LogNormal', 'LogisticNormal', 'LowRankMultivariateNormal', 'LowerCholeskyTransform', 'MixtureSameFamily', 'Multinomial', 'MultivariateNormal', 'NegativeBinomial', 'Normal', 'OneHotCategorical', 'OneHotCategoricalStraightThrough', 'Pareto', 'Poisson', 'PositiveDefiniteTransform', 'PowerTransform', 'RelaxedBernoulli', 'RelaxedOneHotCategorical', 'ReshapeTransform', 'SigmoidTransform', 'SoftmaxTransform', 'SoftplusTransform', 'StackTransform', 'StickBreakingTransform', 'StudentT', 'TanhTransform', 'Transform', 'Transform

In [5]:
help(torch.transpose)

Help on built-in function transpose in module torch:

transpose(...)
    transpose(input, dim0, dim1) -> Tensor

    Returns a tensor that is a transposed version of :attr:`input`.
    The given dimensions :attr:`dim0` and :attr:`dim1` are swapped.

    If :attr:`input` is a strided tensor then the resulting :attr:`out`
    tensor shares its underlying storage with the :attr:`input` tensor, so
    changing the content of one would change the content of the other.

    If :attr:`input` is a :ref:`sparse tensor <sparse-docs>` then the
    resulting :attr:`out` tensor *does not* share the underlying storage
    with the :attr:`input` tensor.

    If :attr:`input` is a :ref:`sparse tensor <sparse-docs>` with compressed
    layout (SparseCSR, SparseBSR, SparseCSC or SparseBSC) the arguments
    :attr:`dim0` and :attr:`dim1` must be both batch dimensions, or must
    both be sparse dimensions. The batch dimensions of a sparse tensor are the
    dimensions preceding the sparse dimensions.

  