- 1. 不带参数的层

In [3]:
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
print(layer(torch.FloatTensor([1,2,3,4,5])))

tensor([-2., -1.,  0.,  1.,  2.])


- 将层作为组件合并到更复杂的模型中

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
print(Y.mean())

tensor(-2.7940e-09, grad_fn=<MeanBackward0>)


- 2. 带参数的层

In [12]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5,3)
print(linear.weight)

print(linear(torch.rand(2, 5)))

Parameter containing:
tensor([[ 0.2891,  1.0796,  0.4706],
        [ 1.8416,  1.7450,  0.5199],
        [-0.2072, -0.2310, -1.3636],
        [-0.4685,  1.3523,  0.4565],
        [ 0.1693, -0.8354,  0.0139]], requires_grad=True)
tensor([[1.2802, 1.1344, 0.5445],
        [0.3294, 1.2820, 0.8439]])


- 可以使用自定义层构建模型，就像使用内置的全连接层一样使用自定义层

In [16]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
print(net(torch.rand(2, 64)))

tensor([[2.8271],
        [7.6806]])
