- 1. 加载和保存张量

In [1]:
import torch

x = torch.arange(4)
torch.save(x, 'x-file')

In [14]:
import torch

x_2 = torch.load('x-file', map_location='cpu', weights_only=True)
print(x_2)

tensor([0, 1, 2, 3])


In [3]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')

In [13]:
x_2, y_2 = torch.load('x-files', map_location='cpu', weights_only=True)
print(x_2, y_2)

tensor([0, 1, 2, 3]) tensor([0., 0., 0., 0.])


In [6]:
mydict = {'x':x, 'y': y}
torch.save(mydict, 'mydict')

In [15]:
mydict_2 = torch.load('mydict', map_location='cpu', weights_only=True)
print(mydict_2)

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}


- 2. 加载和保存模型参数

In [9]:
import torch
from torch import nn
from torch.nn import functional as F

class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

net = MLP()
X = torch.randn(2, 20)
Y = net(X)

print(Y.shape)
print(Y)
print(net.state_dict())

torch.save(net.state_dict(), 'mlp.params')

torch.Size([2, 10])
tensor([[ 0.1027,  0.1632,  0.0075,  0.2104, -0.0399,  0.3447, -0.6240, -0.3149,
         -0.3291, -0.0815],
        [ 0.2654,  0.1568,  0.0547,  0.3923,  0.6545, -0.1111, -0.3155,  0.0139,
         -0.1541, -0.1747]], grad_fn=<AddmmBackward0>)
OrderedDict({'hidden.weight': tensor([[ 0.1767, -0.0103, -0.0200,  ..., -0.1916,  0.1107,  0.1794],
        [ 0.0455, -0.2143, -0.2152,  ..., -0.2195, -0.1986,  0.1570],
        [ 0.0287,  0.0176,  0.1632,  ...,  0.0085, -0.0690,  0.1418],
        ...,
        [ 0.2099,  0.0799,  0.1158,  ...,  0.0029,  0.0675,  0.2127],
        [-0.1230,  0.2065, -0.1323,  ..., -0.0890,  0.1707,  0.0866],
        [-0.0860, -0.1598, -0.0190,  ..., -0.0480, -0.1682, -0.1274]]), 'hidden.bias': tensor([ 0.2053, -0.1485, -0.1157, -0.1723, -0.0012,  0.0637, -0.0496,  0.1308,
        -0.1842,  0.0993,  0.0437,  0.0454, -0.1980,  0.2122,  0.0419, -0.0395,
        -0.1729,  0.0735,  0.1148, -0.1136, -0.1952,  0.0174,  0.1986, -0.1078,
         0.0653

- 恢复模型 不需要随机初始化模型参数，而是直接读取文件中存储的参数

In [16]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params', map_location='cpu', weights_only=True))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [11]:
clone_Y = clone(X)
clone_Y == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])