- 1. 最大汇聚层和平均汇聚层

In [4]:
import torch


def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1] - p_w + 1)

    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                # Y[i, j] = X[i: i+p_h, j: j + p_w].max()
                Y[i, j] = torch.max(X[i: i+p_h, j: j + p_w])
            else:
                # Y[i,j] = X[i: i+p_h, j: j+p_w].mean()
                Y[i,j] = torch.mean(X[i: i+p_h, j: j+p_w])

    return Y

X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
print(pool2d(X, (2, 2)))

tensor([[4., 5.],
        [7., 8.]])


- 2. 填充和步幅

In [8]:
import torch
from torch import nn

X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
print(X)

pool2d = nn.MaxPool2d(3)

'''
MaxPool2d(3), 汇聚层 内核层形状是 3 * 3, 如果没有指定步长 stride 则 stride = kernel_size 这里是3
所以汇聚层滑动的时候, 只有下面一个矩阵, 使用max函数, 结果为 10
[ 0.,  1.,  2.],
[ 4.,  5.,  6.],
[ 8.,  9., 10.]
'''
print(pool2d(X))

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])
tensor([[[[10.]]]])


- 手动设定 填充和步幅

In [9]:
import torch
from torch import nn

pool2d = nn.MaxPool2d(3, padding=1, stride=2)

X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
print(pool2d(X))

tensor([[[[ 5.,  7.],
          [13., 15.]]]])


- 设定一个任意大小的矩形汇聚窗口，并分别设定填充和步幅的高度和宽度

In [11]:
import torch
from torch import nn

pool2d = nn.MaxPool2d((2, 3), padding=(0, 1), stride=(2, 3))

X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
print(pool2d(X))

tensor([[[[ 5.,  7.],
          [13., 15.]]]])


- 3. 多个通道

处理多通道输入数据时，汇聚层在每个输入通道上单独运算，而不是像卷积层一样在通道上对输入进行汇总。 这意味着汇聚层的输出通道数与输入通道数相同

In [21]:
import torch

X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
X = torch.cat([X, X+1], 1)
# print(X)

pool2d = nn.MaxPool2d(3, padding=1, stride=2)
print(pool2d(X))

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])
